version: "3"
services:
    mysqldb:
        restart: always
        container_name: mysqldb
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tfg_db
            - MYSQL_ROOT_HOST=%
        volumes:
            - ../data/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        networks:
          net:
            ipv4_address: 192.168.0.2              
    mongodb:
        restart: always
        container_name: mongodb
        image: mongo:4.4      
        environment:
            - MONGO_INITDB_DATABASE=tfg_mongo
        volumes:
            - ../data/mongo:/docker-entrypoint-initdb.d
        ports:
            - 27017:27017
        networks:
          net:
            ipv4_address: 192.168.0.3           
    web-app:
        restart: on-failure
        container_name: web-app
        image: markendos/tfg-app:latest
        expose:
            - "8443"
        ports:
            - 8443:8443
        networks:
            net:
                ipv4_address: 192.168.0.4
        environment:
            WAIT_HOSTS: mysql:3306, mongo:27017
        depends_on:
            - mysqldb
            - mongodb
    networks:
        net:
        driver: bridge
        ipam:
            config:
              - subnet: 192.168.0.0/16
                gateway: 192.168.0.1            
#    nginx:
#        container_name: nginx
#        build:
#            context: ./nginx
#            dockerfile: Dockerfile
#        restart: always
#        ports:
#            - 80:80
#            - 443:443
#        depends_on:
#            - web-app