version: "3"
services:
    mysqldb:
        restart: always
        container_name: mysqldb
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tfg_db
            - MYSQL_ROOT_HOST=%
        volumes:
            - ../data/sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
    mongodb:
        restart: always
        container_name: mongodb
        image: mongo:4.4      
        environment:
            - MONGO_INITDB_DATABASE=tfg_mongo
        volumes:
            - ../data/mongo:/docker-entrypoint-initdb.d
        ports:
            - "27017:27017"
    web-app:
        restart: on-failure
        container_name: web-app
        image: markendos/tfg-app:dev
        expose:
            - "8081"
        ports:
            - "8081:8081"
        environment:
            WAIT_HOSTS: mysql:3306, mongo:27017
        depends_on:
            - mysqldb
            - mongodb
