name: Preproduction Branch
on:
  pull_request:
    branches: [ pre ]
  push:
    branches: [ pre ]
jobs:
  build:
    name: Test, package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      #- name: Maven Test
      #  run: mvn -B clean test
      - name: Maven Verify
        run: mvn -B -Pprod "-Dmailkey=${{ secrets.GOOGLE_APP_PASSWORD }}" clean verify -DskipTests   
  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO }}
          secrets: |
            "gmail_key=${{ secrets.GOOGLE_APP_PASSWORD }}"
      -   
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    needs: [build, docker]
    steps:      
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
