name: Preproduction Branch
on:
  pull_request:
    branches: [ pre ]
  push:
    branches: [ pre ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Test
        run: mvn -B -Ptest test
      - name: Maven Verify
        run: mvn -B -Pprod clean verify -DskipTests   
  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO }}  
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    needs: [build, docker]
    steps:      
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
  deploy:
    name: Docker Deploy
    runs-on: ubuntu-latest
    needs: [build, docker, automerge]
    steps:
    - uses: actions/checkout@v2
    
    - name: Copy latest docker-compose file to remote server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: docker-compose.yml
        remote: web-app/proyecto-tfg-deploy/docker-compose.yml
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey : ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        
    - name: Copy latest net configuration script to remote server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: scripts/net-config.sh
        remote: web-app/proyecto-tfg-deploy/net-config.sh
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey : ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}        
    
    - name: Pull latest docker images and restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        script: |
            cd web-app/proyecto-tfg-deploy
            docker-compose pull
            docker-compose up -d
            chmod 774 net-config.sh
            ./net-config.sh
            exit
