
name: Main(Production) Branch
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Test
        run: mvn -B -Ptest test
      - name: Maven Verify
        run: mvn -B -Pprod clean verify -DskipTests   
  artifact:
    name: Publish Artifact 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - 
        name: Publish artifact on GitHub Packages
        run: mvn -B -Pprod clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    needs: [build, artifact]
    steps:      
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
