name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Copy docker-comopse
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        source: "docker-compose.yml"
        target: "web-app/proyecto-tfg-deploy/"    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        script: |
            cd web-app/proyecto-tfg-deploy
            docker-compose pull
            docker-compose -d up

