name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: docker-compose.yml
        remote: web-app/proyecto-tfg-deploy/docker-compose.yml
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey : ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        script: |
            cd web-app/proyecto-tfg-deploy
            docker-compose pull
            docker-compose -d up
            exit

